#pragma once

// Generated by Tools/generate_imgui_forward.py; do not edit.
// Call ImGui::IsForwardVersionCompatible() before drawing to detect ABI drift.
// cimgui API definitions are distributed under the MIT License.

#if !defined(NOMINMAX)
#define NOMINMAX
#endif

#if !defined(WIN32_LEAN_AND_MEAN)
#define WIN32_LEAN_AND_MEAN
#endif

#include <Windows.h>

#include <DearModdingUI/API.h>

#undef ERROR
#undef MEM_RELEASE
#undef MAX_PATH
#undef PAGE_EXECUTE_READWRITE
#undef IMAGE_DOS_SIGNATURE

#include <cfloat>
#include <cstdarg>
#include <cstddef>

typedef struct ImVec2_c
{
	float x;
	float y;
} ImVec2_c;

typedef struct ImVec4_c
{
	float x;
	float y;
	float z;
	float w;
} ImVec4_c;

using ImVec2 = ImVec2_c;
using ImVec4 = ImVec4_c;

using ImU32 = unsigned int;
using ImGuiID = unsigned int;
using ImGuiCol = int;
using ImGuiComboFlags = int;
using ImGuiDataType = int;
using ImGuiHoveredFlags = int;
using ImGuiInputTextFlags = int;
using ImGuiSelectableFlags = int;
using ImGuiSliderFlags = int;
using ImGuiTableFlags = int;
using ImGuiTableColumnFlags = int;
using ImGuiTableRowFlags = int;
using ImGuiTreeNodeFlags = int;

struct ImGuiInputTextCallbackData;
using ImGuiInputTextCallback = int (*)(ImGuiInputTextCallbackData* data);

enum ImGuiCol_ : ImGuiCol
{
	ImGuiCol_Text = 0,
	ImGuiCol_TextDisabled = 1,
	ImGuiCol_WindowBg = 2,
	ImGuiCol_ChildBg = 3,
	ImGuiCol_PopupBg = 4,
	ImGuiCol_Border = 5,
	ImGuiCol_BorderShadow = 6,
	ImGuiCol_FrameBg = 7,
	ImGuiCol_FrameBgHovered = 8,
	ImGuiCol_FrameBgActive = 9,
	ImGuiCol_TitleBg = 10,
	ImGuiCol_TitleBgActive = 11,
	ImGuiCol_TitleBgCollapsed = 12,
	ImGuiCol_MenuBarBg = 13,
	ImGuiCol_ScrollbarBg = 14,
	ImGuiCol_ScrollbarGrab = 15,
	ImGuiCol_ScrollbarGrabHovered = 16,
	ImGuiCol_ScrollbarGrabActive = 17,
	ImGuiCol_CheckMark = 18,
	ImGuiCol_CheckboxSelectedBg = 19,
	ImGuiCol_SliderGrab = 20,
	ImGuiCol_SliderGrabActive = 21,
	ImGuiCol_Button = 22,
	ImGuiCol_ButtonHovered = 23,
	ImGuiCol_ButtonActive = 24,
	ImGuiCol_Header = 25,
	ImGuiCol_HeaderHovered = 26,
	ImGuiCol_HeaderActive = 27,
	ImGuiCol_Separator = 28,
	ImGuiCol_SeparatorHovered = 29,
	ImGuiCol_SeparatorActive = 30,
	ImGuiCol_ResizeGrip = 31,
	ImGuiCol_ResizeGripHovered = 32,
	ImGuiCol_ResizeGripActive = 33,
	ImGuiCol_InputTextCursor = 34,
	ImGuiCol_TabHovered = 35,
	ImGuiCol_Tab = 36,
	ImGuiCol_TabSelected = 37,
	ImGuiCol_TabSelectedOverline = 38,
	ImGuiCol_TabDimmed = 39,
	ImGuiCol_TabDimmedSelected = 40,
	ImGuiCol_TabDimmedSelectedOverline = 41,
	ImGuiCol_DockingPreview = 42,
	ImGuiCol_DockingEmptyBg = 43,
	ImGuiCol_PlotLines = 44,
	ImGuiCol_PlotLinesHovered = 45,
	ImGuiCol_PlotHistogram = 46,
	ImGuiCol_PlotHistogramHovered = 47,
	ImGuiCol_TableHeaderBg = 48,
	ImGuiCol_TableBorderStrong = 49,
	ImGuiCol_TableBorderLight = 50,
	ImGuiCol_TableRowBg = 51,
	ImGuiCol_TableRowBgAlt = 52,
	ImGuiCol_TextLink = 53,
	ImGuiCol_TextSelectedBg = 54,
	ImGuiCol_TreeLines = 55,
	ImGuiCol_DragDropTarget = 56,
	ImGuiCol_DragDropTargetBg = 57,
	ImGuiCol_UnsavedMarker = 58,
	ImGuiCol_NavCursor = 59,
	ImGuiCol_NavWindowingHighlight = 60,
	ImGuiCol_NavWindowingDimBg = 61,
	ImGuiCol_ModalWindowDimBg = 62,
	ImGuiCol_COUNT = 63
};

enum ImGuiComboFlags_ : ImGuiComboFlags
{
	ImGuiComboFlags_None = 0,
	ImGuiComboFlags_PopupAlignLeft = 1 << 0,
	ImGuiComboFlags_HeightSmall = 1 << 1,
	ImGuiComboFlags_HeightRegular = 1 << 2,
	ImGuiComboFlags_HeightLarge = 1 << 3,
	ImGuiComboFlags_HeightLargest = 1 << 4,
	ImGuiComboFlags_NoArrowButton = 1 << 5,
	ImGuiComboFlags_NoPreview = 1 << 6,
	ImGuiComboFlags_WidthFitPreview = 1 << 7,
	ImGuiComboFlags_HeightMask_ = ImGuiComboFlags_HeightSmall | ImGuiComboFlags_HeightRegular | ImGuiComboFlags_HeightLarge | ImGuiComboFlags_HeightLargest
};

enum ImGuiDataType_ : ImGuiDataType
{
	ImGuiDataType_S8 = 0,
	ImGuiDataType_U8 = 1,
	ImGuiDataType_S16 = 2,
	ImGuiDataType_U16 = 3,
	ImGuiDataType_S32 = 4,
	ImGuiDataType_U32 = 5,
	ImGuiDataType_S64 = 6,
	ImGuiDataType_U64 = 7,
	ImGuiDataType_Float = 8,
	ImGuiDataType_Double = 9,
	ImGuiDataType_Bool = 10,
	ImGuiDataType_String = 11,
	ImGuiDataType_COUNT = 12
};

enum ImGuiHoveredFlags_ : ImGuiHoveredFlags
{
	ImGuiHoveredFlags_None = 0,
	ImGuiHoveredFlags_ChildWindows = 1 << 0,
	ImGuiHoveredFlags_RootWindow = 1 << 1,
	ImGuiHoveredFlags_AnyWindow = 1 << 2,
	ImGuiHoveredFlags_NoPopupHierarchy = 1 << 3,
	ImGuiHoveredFlags_DockHierarchy = 1 << 4,
	ImGuiHoveredFlags_AllowWhenBlockedByPopup = 1 << 5,
	ImGuiHoveredFlags_AllowWhenBlockedByActiveItem = 1 << 7,
	ImGuiHoveredFlags_AllowWhenOverlappedByItem = 1 << 8,
	ImGuiHoveredFlags_AllowWhenOverlappedByWindow = 1 << 9,
	ImGuiHoveredFlags_AllowWhenDisabled = 1 << 10,
	ImGuiHoveredFlags_NoNavOverride = 1 << 11,
	ImGuiHoveredFlags_AllowWhenOverlapped = ImGuiHoveredFlags_AllowWhenOverlappedByItem | ImGuiHoveredFlags_AllowWhenOverlappedByWindow,
	ImGuiHoveredFlags_RectOnly = ImGuiHoveredFlags_AllowWhenBlockedByPopup | ImGuiHoveredFlags_AllowWhenBlockedByActiveItem | ImGuiHoveredFlags_AllowWhenOverlapped,
	ImGuiHoveredFlags_RootAndChildWindows = ImGuiHoveredFlags_RootWindow | ImGuiHoveredFlags_ChildWindows,
	ImGuiHoveredFlags_ForTooltip = 1 << 12,
	ImGuiHoveredFlags_Stationary = 1 << 13,
	ImGuiHoveredFlags_DelayNone = 1 << 14,
	ImGuiHoveredFlags_DelayShort = 1 << 15,
	ImGuiHoveredFlags_DelayNormal = 1 << 16,
	ImGuiHoveredFlags_NoSharedDelay = 1 << 17
};

enum ImGuiInputTextFlags_ : ImGuiInputTextFlags
{
	ImGuiInputTextFlags_None = 0,
	ImGuiInputTextFlags_CharsDecimal = 1 << 0,
	ImGuiInputTextFlags_CharsHexadecimal = 1 << 1,
	ImGuiInputTextFlags_CharsScientific = 1 << 2,
	ImGuiInputTextFlags_CharsUppercase = 1 << 3,
	ImGuiInputTextFlags_CharsNoBlank = 1 << 4,
	ImGuiInputTextFlags_AllowTabInput = 1 << 5,
	ImGuiInputTextFlags_EnterReturnsTrue = 1 << 6,
	ImGuiInputTextFlags_EscapeClearsAll = 1 << 7,
	ImGuiInputTextFlags_CtrlEnterForNewLine = 1 << 8,
	ImGuiInputTextFlags_ReadOnly = 1 << 9,
	ImGuiInputTextFlags_Password = 1 << 10,
	ImGuiInputTextFlags_AlwaysOverwrite = 1 << 11,
	ImGuiInputTextFlags_AutoSelectAll = 1 << 12,
	ImGuiInputTextFlags_ParseEmptyRefVal = 1 << 13,
	ImGuiInputTextFlags_DisplayEmptyRefVal = 1 << 14,
	ImGuiInputTextFlags_NoHorizontalScroll = 1 << 15,
	ImGuiInputTextFlags_NoUndoRedo = 1 << 16,
	ImGuiInputTextFlags_ElideLeft = 1 << 17,
	ImGuiInputTextFlags_CallbackCompletion = 1 << 18,
	ImGuiInputTextFlags_CallbackHistory = 1 << 19,
	ImGuiInputTextFlags_CallbackAlways = 1 << 20,
	ImGuiInputTextFlags_CallbackCharFilter = 1 << 21,
	ImGuiInputTextFlags_CallbackResize = 1 << 22,
	ImGuiInputTextFlags_CallbackEdit = 1 << 23,
	ImGuiInputTextFlags_WordWrap = 1 << 24
};

enum ImGuiSelectableFlags_ : ImGuiSelectableFlags
{
	ImGuiSelectableFlags_None = 0,
	ImGuiSelectableFlags_NoAutoClosePopups = 1 << 0,
	ImGuiSelectableFlags_SpanAllColumns = 1 << 1,
	ImGuiSelectableFlags_AllowDoubleClick = 1 << 2,
	ImGuiSelectableFlags_Disabled = 1 << 3,
	ImGuiSelectableFlags_AllowOverlap = 1 << 4,
	ImGuiSelectableFlags_Highlight = 1 << 5,
	ImGuiSelectableFlags_SelectOnNav = 1 << 6
};

enum ImGuiSliderFlags_ : ImGuiSliderFlags
{
	ImGuiSliderFlags_None = 0,
	ImGuiSliderFlags_Logarithmic = 1 << 5,
	ImGuiSliderFlags_NoRoundToFormat = 1 << 6,
	ImGuiSliderFlags_NoInput = 1 << 7,
	ImGuiSliderFlags_WrapAround = 1 << 8,
	ImGuiSliderFlags_ClampOnInput = 1 << 9,
	ImGuiSliderFlags_ClampZeroRange = 1 << 10,
	ImGuiSliderFlags_NoSpeedTweaks = 1 << 11,
	ImGuiSliderFlags_ColorMarkers = 1 << 12,
	ImGuiSliderFlags_AlwaysClamp = ImGuiSliderFlags_ClampOnInput | ImGuiSliderFlags_ClampZeroRange,
	ImGuiSliderFlags_InvalidMask_ = 0x7000000F
};

enum ImGuiTableFlags_ : ImGuiTableFlags
{
	ImGuiTableFlags_None = 0,
	ImGuiTableFlags_Resizable = 1 << 0,
	ImGuiTableFlags_Reorderable = 1 << 1,
	ImGuiTableFlags_Hideable = 1 << 2,
	ImGuiTableFlags_Sortable = 1 << 3,
	ImGuiTableFlags_NoSavedSettings = 1 << 4,
	ImGuiTableFlags_ContextMenuInBody = 1 << 5,
	ImGuiTableFlags_RowBg = 1 << 6,
	ImGuiTableFlags_BordersInnerH = 1 << 7,
	ImGuiTableFlags_BordersOuterH = 1 << 8,
	ImGuiTableFlags_BordersInnerV = 1 << 9,
	ImGuiTableFlags_BordersOuterV = 1 << 10,
	ImGuiTableFlags_BordersH = ImGuiTableFlags_BordersInnerH | ImGuiTableFlags_BordersOuterH,
	ImGuiTableFlags_BordersV = ImGuiTableFlags_BordersInnerV | ImGuiTableFlags_BordersOuterV,
	ImGuiTableFlags_BordersInner = ImGuiTableFlags_BordersInnerV | ImGuiTableFlags_BordersInnerH,
	ImGuiTableFlags_BordersOuter = ImGuiTableFlags_BordersOuterV | ImGuiTableFlags_BordersOuterH,
	ImGuiTableFlags_Borders = ImGuiTableFlags_BordersInner | ImGuiTableFlags_BordersOuter,
	ImGuiTableFlags_NoBordersInBody = 1 << 11,
	ImGuiTableFlags_NoBordersInBodyUntilResize = 1 << 12,
	ImGuiTableFlags_SizingFixedFit = 1 << 13,
	ImGuiTableFlags_SizingFixedSame = 2 << 13,
	ImGuiTableFlags_SizingStretchProp = 3 << 13,
	ImGuiTableFlags_SizingStretchSame = 4 << 13,
	ImGuiTableFlags_NoHostExtendX = 1 << 16,
	ImGuiTableFlags_NoHostExtendY = 1 << 17,
	ImGuiTableFlags_NoKeepColumnsVisible = 1 << 18,
	ImGuiTableFlags_PreciseWidths = 1 << 19,
	ImGuiTableFlags_NoClip = 1 << 20,
	ImGuiTableFlags_PadOuterX = 1 << 21,
	ImGuiTableFlags_NoPadOuterX = 1 << 22,
	ImGuiTableFlags_NoPadInnerX = 1 << 23,
	ImGuiTableFlags_ScrollX = 1 << 24,
	ImGuiTableFlags_ScrollY = 1 << 25,
	ImGuiTableFlags_SortMulti = 1 << 26,
	ImGuiTableFlags_SortTristate = 1 << 27,
	ImGuiTableFlags_HighlightHoveredColumn = 1 << 28,
	ImGuiTableFlags_SizingMask_ = ImGuiTableFlags_SizingFixedFit | ImGuiTableFlags_SizingFixedSame | ImGuiTableFlags_SizingStretchProp | ImGuiTableFlags_SizingStretchSame
};

enum ImGuiTableColumnFlags_ : ImGuiTableColumnFlags
{
	ImGuiTableColumnFlags_None = 0,
	ImGuiTableColumnFlags_Disabled = 1 << 0,
	ImGuiTableColumnFlags_DefaultHide = 1 << 1,
	ImGuiTableColumnFlags_DefaultSort = 1 << 2,
	ImGuiTableColumnFlags_WidthStretch = 1 << 3,
	ImGuiTableColumnFlags_WidthFixed = 1 << 4,
	ImGuiTableColumnFlags_NoResize = 1 << 5,
	ImGuiTableColumnFlags_NoReorder = 1 << 6,
	ImGuiTableColumnFlags_NoHide = 1 << 7,
	ImGuiTableColumnFlags_NoClip = 1 << 8,
	ImGuiTableColumnFlags_NoSort = 1 << 9,
	ImGuiTableColumnFlags_NoSortAscending = 1 << 10,
	ImGuiTableColumnFlags_NoSortDescending = 1 << 11,
	ImGuiTableColumnFlags_NoHeaderLabel = 1 << 12,
	ImGuiTableColumnFlags_NoHeaderWidth = 1 << 13,
	ImGuiTableColumnFlags_PreferSortAscending = 1 << 14,
	ImGuiTableColumnFlags_PreferSortDescending = 1 << 15,
	ImGuiTableColumnFlags_IndentEnable = 1 << 16,
	ImGuiTableColumnFlags_IndentDisable = 1 << 17,
	ImGuiTableColumnFlags_AngledHeader = 1 << 18,
	ImGuiTableColumnFlags_IsEnabled = 1 << 24,
	ImGuiTableColumnFlags_IsVisible = 1 << 25,
	ImGuiTableColumnFlags_IsSorted = 1 << 26,
	ImGuiTableColumnFlags_IsHovered = 1 << 27,
	ImGuiTableColumnFlags_WidthMask_ = ImGuiTableColumnFlags_WidthStretch | ImGuiTableColumnFlags_WidthFixed,
	ImGuiTableColumnFlags_IndentMask_ = ImGuiTableColumnFlags_IndentEnable | ImGuiTableColumnFlags_IndentDisable,
	ImGuiTableColumnFlags_StatusMask_ = ImGuiTableColumnFlags_IsEnabled | ImGuiTableColumnFlags_IsVisible | ImGuiTableColumnFlags_IsSorted | ImGuiTableColumnFlags_IsHovered,
	ImGuiTableColumnFlags_NoDirectResize_ = 1 << 30
};

enum ImGuiTableRowFlags_ : ImGuiTableRowFlags
{
	ImGuiTableRowFlags_None = 0,
	ImGuiTableRowFlags_Headers = 1 << 0
};

enum ImGuiTreeNodeFlags_ : ImGuiTreeNodeFlags
{
	ImGuiTreeNodeFlags_None = 0,
	ImGuiTreeNodeFlags_Selected = 1 << 0,
	ImGuiTreeNodeFlags_Framed = 1 << 1,
	ImGuiTreeNodeFlags_AllowOverlap = 1 << 2,
	ImGuiTreeNodeFlags_NoTreePushOnOpen = 1 << 3,
	ImGuiTreeNodeFlags_NoAutoOpenOnLog = 1 << 4,
	ImGuiTreeNodeFlags_DefaultOpen = 1 << 5,
	ImGuiTreeNodeFlags_OpenOnDoubleClick = 1 << 6,
	ImGuiTreeNodeFlags_OpenOnArrow = 1 << 7,
	ImGuiTreeNodeFlags_Leaf = 1 << 8,
	ImGuiTreeNodeFlags_Bullet = 1 << 9,
	ImGuiTreeNodeFlags_FramePadding = 1 << 10,
	ImGuiTreeNodeFlags_SpanAvailWidth = 1 << 11,
	ImGuiTreeNodeFlags_SpanFullWidth = 1 << 12,
	ImGuiTreeNodeFlags_SpanLabelWidth = 1 << 13,
	ImGuiTreeNodeFlags_SpanAllColumns = 1 << 14,
	ImGuiTreeNodeFlags_LabelSpanAllColumns = 1 << 15,
	ImGuiTreeNodeFlags_NavLeftJumpsToParent = 1 << 17,
	ImGuiTreeNodeFlags_CollapsingHeader = ImGuiTreeNodeFlags_Framed | ImGuiTreeNodeFlags_NoTreePushOnOpen | ImGuiTreeNodeFlags_NoAutoOpenOnLog,
	ImGuiTreeNodeFlags_DrawLinesNone = 1 << 18,
	ImGuiTreeNodeFlags_DrawLinesFull = 1 << 19,
	ImGuiTreeNodeFlags_DrawLinesToNodes = 1 << 20
};

namespace ImGui
{
	inline constexpr uint32_t kForwardImGuiVersionNum{ 19291u };

	namespace detail
	{
		inline HMODULE HostModule() noexcept
		{
			static const HMODULE module = GetModuleHandleW(L"DearModdingUI.dll");
			return module;
		}

		template <class Function>
		Function Resolve(const char* symbol) noexcept
		{
			const auto module = HostModule();
			return module ? reinterpret_cast<Function>(GetProcAddress(module, symbol)) : nullptr;
		}
	}

	[[nodiscard]] inline uint32_t GetHostImGuiVersionNum() noexcept
	{
		using Function = uint32_t (DMUI_CALL*)(void) noexcept;
		static const Function function = detail::Resolve<Function>("DMUI_GetImGuiVersionNum");
		return function ? function() : 0u;
	}

	[[nodiscard]] inline bool IsForwardVersionCompatible() noexcept
	{
		return GetHostImGuiVersionNum() == kForwardImGuiVersionNum;
	}

	[[nodiscard]] inline DMUI_Result GetStyleMetrics(DMUI_StyleMetrics& metrics) noexcept
	{
		using Function = DMUI_Result (DMUI_CALL*)(DMUI_StyleMetrics*) noexcept;
		static const Function function = detail::Resolve<Function>("DMUI_GetStyleMetrics");
		metrics = {};
		metrics.structSize = sizeof(metrics);
		return function ? function(&metrics) : DMUI_RESULT_UNSUPPORTED_ABI;
	}

	[[nodiscard]] inline bool BeginCombo(const char* label, const char* preview_value, ImGuiComboFlags flags = 0) noexcept
	{
		using Function = bool (*)(const char*, const char*, ImGuiComboFlags);
		static const Function function = detail::Resolve<Function>("igBeginCombo");
		if (!function)
			return false;
		return function(label, preview_value, flags);
	}

	inline void BeginDisabled(bool disabled = true) noexcept
	{
		using Function = void (*)(bool);
		static const Function function = detail::Resolve<Function>("igBeginDisabled");
		if (function)
			function(disabled);
	}

	[[nodiscard]] inline bool BeginTable(const char* str_id, int columns, ImGuiTableFlags flags = 0, const ImVec2& outer_size = ImVec2(0.0f,0.0f), float inner_width = 0.0f) noexcept
	{
		using Function = bool (*)(const char*, int, ImGuiTableFlags, const ImVec2, float);
		static const Function function = detail::Resolve<Function>("igBeginTable");
		if (!function)
			return false;
		return function(str_id, columns, flags, outer_size, inner_width);
	}

	[[nodiscard]] inline bool BeginTooltip() noexcept
	{
		using Function = bool (*)(void);
		static const Function function = detail::Resolve<Function>("igBeginTooltip");
		if (!function)
			return false;
		return function();
	}

	[[nodiscard]] inline bool Button(const char* label, const ImVec2& size = ImVec2(0,0)) noexcept
	{
		using Function = bool (*)(const char*, const ImVec2);
		static const Function function = detail::Resolve<Function>("igButton");
		if (!function)
			return false;
		return function(label, size);
	}

	[[nodiscard]] inline ImVec2 CalcTextSize(const char* text, const char* text_end = nullptr, bool hide_text_after_double_hash = false, float wrap_width = -1.0f) noexcept
	{
		using Function = ImVec2 (*)(const char*, const char*, bool, float);
		static const Function function = detail::Resolve<Function>("igCalcTextSize");
		if (!function)
			return {};
		return function(text, text_end, hide_text_after_double_hash, wrap_width);
	}

	[[nodiscard]] inline bool Checkbox(const char* label, bool* v) noexcept
	{
		using Function = bool (*)(const char*, bool*);
		static const Function function = detail::Resolve<Function>("igCheckbox");
		if (!function)
			return false;
		return function(label, v);
	}

	[[nodiscard]] inline bool CollapsingHeader(const char* label, ImGuiTreeNodeFlags flags = 0) noexcept
	{
		using Function = bool (*)(const char*, ImGuiTreeNodeFlags);
		static const Function function = detail::Resolve<Function>("igCollapsingHeader_TreeNodeFlags");
		if (!function)
			return false;
		return function(label, flags);
	}

	[[nodiscard]] inline bool CollapsingHeader(const char* label, bool* p_visible, ImGuiTreeNodeFlags flags = 0) noexcept
	{
		using Function = bool (*)(const char*, bool*, ImGuiTreeNodeFlags);
		static const Function function = detail::Resolve<Function>("igCollapsingHeader_BoolPtr");
		if (!function)
			return false;
		return function(label, p_visible, flags);
	}

	[[nodiscard]] inline bool DragScalar(const char* label, ImGuiDataType data_type, void* p_data, float v_speed = 1.0f, const void* p_min = nullptr, const void* p_max = nullptr, const char* format = nullptr, ImGuiSliderFlags flags = 0) noexcept
	{
		using Function = bool (*)(const char*, ImGuiDataType, void*, float, const void*, const void*, const char*, ImGuiSliderFlags);
		static const Function function = detail::Resolve<Function>("igDragScalar");
		if (!function)
			return false;
		return function(label, data_type, p_data, v_speed, p_min, p_max, format, flags);
	}

	inline void Dummy(const ImVec2& size) noexcept
	{
		using Function = void (*)(const ImVec2);
		static const Function function = detail::Resolve<Function>("igDummy");
		if (function)
			function(size);
	}

	inline void EndCombo() noexcept
	{
		using Function = void (*)(void);
		static const Function function = detail::Resolve<Function>("igEndCombo");
		if (function)
			function();
	}

	inline void EndDisabled() noexcept
	{
		using Function = void (*)(void);
		static const Function function = detail::Resolve<Function>("igEndDisabled");
		if (function)
			function();
	}

	inline void EndTable() noexcept
	{
		using Function = void (*)(void);
		static const Function function = detail::Resolve<Function>("igEndTable");
		if (function)
			function();
	}

	inline void EndTooltip() noexcept
	{
		using Function = void (*)(void);
		static const Function function = detail::Resolve<Function>("igEndTooltip");
		if (function)
			function();
	}

	[[nodiscard]] inline ImVec2 GetContentRegionAvail() noexcept
	{
		using Function = ImVec2 (*)(void);
		static const Function function = detail::Resolve<Function>("igGetContentRegionAvail");
		if (!function)
			return {};
		return function();
	}

	[[nodiscard]] inline ImVec2 GetCursorScreenPos() noexcept
	{
		using Function = ImVec2 (*)(void);
		static const Function function = detail::Resolve<Function>("igGetCursorScreenPos");
		if (!function)
			return {};
		return function();
	}

	[[nodiscard]] inline float GetFontSize() noexcept
	{
		using Function = float (*)(void);
		static const Function function = detail::Resolve<Function>("igGetFontSize");
		if (!function)
			return 0.0f;
		return function();
	}

	[[nodiscard]] inline float GetFrameHeight() noexcept
	{
		using Function = float (*)(void);
		static const Function function = detail::Resolve<Function>("igGetFrameHeight");
		if (!function)
			return 0.0f;
		return function();
	}

	[[nodiscard]] inline const ImVec4& GetStyleColorVec4(ImGuiCol idx) noexcept
	{
		using Function = const ImVec4* (*)(ImGuiCol);
		static const Function function = detail::Resolve<Function>("igGetStyleColorVec4");
		static const ImVec4 fallback{};
		if (!function)
			return fallback;
		const auto result = function(idx);
		return result ? *result : fallback;
	}

	[[nodiscard]] inline float GetTextLineHeightWithSpacing() noexcept
	{
		using Function = float (*)(void);
		static const Function function = detail::Resolve<Function>("igGetTextLineHeightWithSpacing");
		if (!function)
			return 0.0f;
		return function();
	}

	inline void Indent(float indent_w = 0.0f) noexcept
	{
		using Function = void (*)(float);
		static const Function function = detail::Resolve<Function>("igIndent");
		if (function)
			function(indent_w);
	}

	[[nodiscard]] inline bool InputScalar(const char* label, ImGuiDataType data_type, void* p_data, const void* p_step = nullptr, const void* p_step_fast = nullptr, const char* format = nullptr, ImGuiInputTextFlags flags = 0) noexcept
	{
		using Function = bool (*)(const char*, ImGuiDataType, void*, const void*, const void*, const char*, ImGuiInputTextFlags);
		static const Function function = detail::Resolve<Function>("igInputScalar");
		if (!function)
			return false;
		return function(label, data_type, p_data, p_step, p_step_fast, format, flags);
	}

	[[nodiscard]] inline bool InputText(const char* label, char* buf, std::size_t buf_size, ImGuiInputTextFlags flags = 0, ImGuiInputTextCallback callback = nullptr, void* user_data = nullptr) noexcept
	{
		using Function = bool (*)(const char*, char*, std::size_t, ImGuiInputTextFlags, ImGuiInputTextCallback, void*);
		static const Function function = detail::Resolve<Function>("igInputText");
		if (!function)
			return false;
		return function(label, buf, buf_size, flags, callback, user_data);
	}

	[[nodiscard]] inline bool InputTextWithHint(const char* label, const char* hint, char* buf, std::size_t buf_size, ImGuiInputTextFlags flags = 0, ImGuiInputTextCallback callback = nullptr, void* user_data = nullptr) noexcept
	{
		using Function = bool (*)(const char*, const char*, char*, std::size_t, ImGuiInputTextFlags, ImGuiInputTextCallback, void*);
		static const Function function = detail::Resolve<Function>("igInputTextWithHint");
		if (!function)
			return false;
		return function(label, hint, buf, buf_size, flags, callback, user_data);
	}

	[[nodiscard]] inline bool IsItemHovered(ImGuiHoveredFlags flags = 0) noexcept
	{
		using Function = bool (*)(ImGuiHoveredFlags);
		static const Function function = detail::Resolve<Function>("igIsItemHovered");
		if (!function)
			return false;
		return function(flags);
	}

	inline void PlotLines(const char* label, const float* values, int values_count, int values_offset = 0, const char* overlay_text = nullptr, float scale_min = FLT_MAX, float scale_max = FLT_MAX, ImVec2 graph_size = ImVec2(0,0), int stride = sizeof(float)) noexcept
	{
		using Function = void (*)(const char*, const float*, int, int, const char*, float, float, ImVec2, int);
		static const Function function = detail::Resolve<Function>("igPlotLines_FloatPtr");
		if (function)
			function(label, values, values_count, values_offset, overlay_text, scale_min, scale_max, graph_size, stride);
	}

	inline void PlotLines(const char* label, float(*values_getter)(void* data,int idx), void* data, int values_count, int values_offset = 0, const char* overlay_text = nullptr, float scale_min = FLT_MAX, float scale_max = FLT_MAX, ImVec2 graph_size = ImVec2(0,0)) noexcept
	{
		using Function = void (*)(const char*, float(*)(void* data,int idx), void*, int, int, const char*, float, float, ImVec2);
		static const Function function = detail::Resolve<Function>("igPlotLines_FnFloatPtr");
		if (function)
			function(label, values_getter, data, values_count, values_offset, overlay_text, scale_min, scale_max, graph_size);
	}

	inline void PopID() noexcept
	{
		using Function = void (*)(void);
		static const Function function = detail::Resolve<Function>("igPopID");
		if (function)
			function();
	}

	inline void PopStyleColor(int count = 1) noexcept
	{
		using Function = void (*)(int);
		static const Function function = detail::Resolve<Function>("igPopStyleColor");
		if (function)
			function(count);
	}

	inline void ProgressBar(float fraction, const ImVec2& size_arg = ImVec2(-FLT_MIN,0), const char* overlay = nullptr) noexcept
	{
		using Function = void (*)(float, const ImVec2, const char*);
		static const Function function = detail::Resolve<Function>("igProgressBar");
		if (function)
			function(fraction, size_arg, overlay);
	}

	inline void PushID(const char* str_id) noexcept
	{
		using Function = void (*)(const char*);
		static const Function function = detail::Resolve<Function>("igPushID_Str");
		if (function)
			function(str_id);
	}

	inline void PushID(const char* str_id_begin, const char* str_id_end) noexcept
	{
		using Function = void (*)(const char*, const char*);
		static const Function function = detail::Resolve<Function>("igPushID_StrStr");
		if (function)
			function(str_id_begin, str_id_end);
	}

	inline void PushID(const void* ptr_id) noexcept
	{
		using Function = void (*)(const void*);
		static const Function function = detail::Resolve<Function>("igPushID_Ptr");
		if (function)
			function(ptr_id);
	}

	inline void PushID(int int_id) noexcept
	{
		using Function = void (*)(int);
		static const Function function = detail::Resolve<Function>("igPushID_Int");
		if (function)
			function(int_id);
	}

	inline void PushStyleColor(ImGuiCol idx, ImU32 col) noexcept
	{
		using Function = void (*)(ImGuiCol, ImU32);
		static const Function function = detail::Resolve<Function>("igPushStyleColor_U32");
		if (function)
			function(idx, col);
	}

	inline void PushStyleColor(ImGuiCol idx, const ImVec4& col) noexcept
	{
		using Function = void (*)(ImGuiCol, const ImVec4);
		static const Function function = detail::Resolve<Function>("igPushStyleColor_Vec4");
		if (function)
			function(idx, col);
	}

	inline void SameLine(float offset_from_start_x = 0.0f, float spacing = -1.0f) noexcept
	{
		using Function = void (*)(float, float);
		static const Function function = detail::Resolve<Function>("igSameLine");
		if (function)
			function(offset_from_start_x, spacing);
	}

	[[nodiscard]] inline bool Selectable(const char* label, bool selected = false, ImGuiSelectableFlags flags = 0, const ImVec2& size = ImVec2(0,0)) noexcept
	{
		using Function = bool (*)(const char*, bool, ImGuiSelectableFlags, const ImVec2);
		static const Function function = detail::Resolve<Function>("igSelectable_Bool");
		if (!function)
			return false;
		return function(label, selected, flags, size);
	}

	[[nodiscard]] inline bool Selectable(const char* label, bool* p_selected, ImGuiSelectableFlags flags = 0, const ImVec2& size = ImVec2(0,0)) noexcept
	{
		using Function = bool (*)(const char*, bool*, ImGuiSelectableFlags, const ImVec2);
		static const Function function = detail::Resolve<Function>("igSelectable_BoolPtr");
		if (!function)
			return false;
		return function(label, p_selected, flags, size);
	}

	inline void Separator() noexcept
	{
		using Function = void (*)(void);
		static const Function function = detail::Resolve<Function>("igSeparator");
		if (function)
			function();
	}

	inline void SetClipboardText(const char* text) noexcept
	{
		using Function = void (*)(const char*);
		static const Function function = detail::Resolve<Function>("igSetClipboardText");
		if (function)
			function(text);
	}

	inline void SetCursorScreenPos(const ImVec2& pos) noexcept
	{
		using Function = void (*)(const ImVec2);
		static const Function function = detail::Resolve<Function>("igSetCursorScreenPos");
		if (function)
			function(pos);
	}

	inline void SetItemDefaultFocus() noexcept
	{
		using Function = void (*)(void);
		static const Function function = detail::Resolve<Function>("igSetItemDefaultFocus");
		if (function)
			function();
	}

	inline void SetNextItemWidth(float item_width) noexcept
	{
		using Function = void (*)(float);
		static const Function function = detail::Resolve<Function>("igSetNextItemWidth");
		if (function)
			function(item_width);
	}

	inline void SetTooltip(const char* fmt, ...) noexcept
	{
		using Function = void (*)(const char*, std::va_list);
		static const Function function = detail::Resolve<Function>("igSetTooltipV");
		if (!function)
			return;
		std::va_list args;
		va_start(args, fmt);
		function(fmt, args);
		va_end(args);
	}

	[[nodiscard]] inline bool SliderScalar(const char* label, ImGuiDataType data_type, void* p_data, const void* p_min, const void* p_max, const char* format = nullptr, ImGuiSliderFlags flags = 0) noexcept
	{
		using Function = bool (*)(const char*, ImGuiDataType, void*, const void*, const void*, const char*, ImGuiSliderFlags);
		static const Function function = detail::Resolve<Function>("igSliderScalar");
		if (!function)
			return false;
		return function(label, data_type, p_data, p_min, p_max, format, flags);
	}

	inline void Spacing() noexcept
	{
		using Function = void (*)(void);
		static const Function function = detail::Resolve<Function>("igSpacing");
		if (function)
			function();
	}

	inline void TableHeadersRow() noexcept
	{
		using Function = void (*)(void);
		static const Function function = detail::Resolve<Function>("igTableHeadersRow");
		if (function)
			function();
	}

	[[nodiscard]] inline bool TableNextColumn() noexcept
	{
		using Function = bool (*)(void);
		static const Function function = detail::Resolve<Function>("igTableNextColumn");
		if (!function)
			return false;
		return function();
	}

	inline void TableNextRow(ImGuiTableRowFlags row_flags = 0, float min_row_height = 0.0f) noexcept
	{
		using Function = void (*)(ImGuiTableRowFlags, float);
		static const Function function = detail::Resolve<Function>("igTableNextRow");
		if (function)
			function(row_flags, min_row_height);
	}

	[[nodiscard]] inline bool TableSetColumnIndex(int column_n) noexcept
	{
		using Function = bool (*)(int);
		static const Function function = detail::Resolve<Function>("igTableSetColumnIndex");
		if (!function)
			return false;
		return function(column_n);
	}

	inline void TableSetupColumn(const char* label, ImGuiTableColumnFlags flags = 0, float init_width_or_weight = 0.0f, ImGuiID user_data = 0) noexcept
	{
		using Function = void (*)(const char*, ImGuiTableColumnFlags, float, ImGuiID);
		static const Function function = detail::Resolve<Function>("igTableSetupColumn");
		if (function)
			function(label, flags, init_width_or_weight, user_data);
	}

	inline void TableSetupScrollFreeze(int cols, int rows) noexcept
	{
		using Function = void (*)(int, int);
		static const Function function = detail::Resolve<Function>("igTableSetupScrollFreeze");
		if (function)
			function(cols, rows);
	}

	inline void Text(const char* fmt, ...) noexcept
	{
		using Function = void (*)(const char*, std::va_list);
		static const Function function = detail::Resolve<Function>("igTextV");
		if (!function)
			return;
		std::va_list args;
		va_start(args, fmt);
		function(fmt, args);
		va_end(args);
	}

	inline void TextColored(const ImVec4& col, const char* fmt, ...) noexcept
	{
		using Function = void (*)(const ImVec4, const char*, std::va_list);
		static const Function function = detail::Resolve<Function>("igTextColoredV");
		if (!function)
			return;
		std::va_list args;
		va_start(args, fmt);
		function(col, fmt, args);
		va_end(args);
	}

	inline void TextDisabled(const char* fmt, ...) noexcept
	{
		using Function = void (*)(const char*, std::va_list);
		static const Function function = detail::Resolve<Function>("igTextDisabledV");
		if (!function)
			return;
		std::va_list args;
		va_start(args, fmt);
		function(fmt, args);
		va_end(args);
	}

	inline void TextUnformatted(const char* text, const char* text_end = nullptr) noexcept
	{
		using Function = void (*)(const char*, const char*);
		static const Function function = detail::Resolve<Function>("igTextUnformatted");
		if (function)
			function(text, text_end);
	}

	inline void TextWrapped(const char* fmt, ...) noexcept
	{
		using Function = void (*)(const char*, std::va_list);
		static const Function function = detail::Resolve<Function>("igTextWrappedV");
		if (!function)
			return;
		std::va_list args;
		va_start(args, fmt);
		function(fmt, args);
		va_end(args);
	}

	inline void Unindent(float indent_w = 0.0f) noexcept
	{
		using Function = void (*)(float);
		static const Function function = detail::Resolve<Function>("igUnindent");
		if (function)
			function(indent_w);
	}

	inline void NewLine() noexcept
	{
		using Function = void (*)(void);
		static const Function function = detail::Resolve<Function>("igNewLine");
		if (function)
			function();
	}
}
